### ISSUE TITLE
Quick Links and Tutorial section - Links all go to the root Medium, YouTube, and GitHub Sites

### ISSUE THREAD

**Issue by sosentos** [fathomnet/community-feedback#102]
The links are the same for all of the topics in the Quick Links and Tutorial Section of the website.

For example I would change the "How to download data from FathomNet:" Medium link to point directly to this article: https://medium.com/fathomnet/how-to-download-images-and-bounding-boxes-from-fathomnet-using-python-283ff32c975f

I tried poking around to see if the website code was in a public repo and I could make a pull request but didn't find it.

**Comment by kakanikatija** [comment]
similar to https://github.com/fathomnet/community-feedback/issues/16. we're going to integrate blogs and other content into the main site, so i'll close this issue.
