### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by kakanikatija** [fathomnet/community-feedback#11]
The privacy policy is currently linked to MBARI's.

**Comment by kakanikatija** [comment]
@ermbutler do we need a privacy policy?

**Comment by ermbutler** [comment]
I was just scanning the site - and reading around. You may want to get more opinions but my take, is that it would be worth having its own page.

It could generally be the same policy but slightly tailored to the nature of this site which does contain user accounts.

You could simply say this is a feature related to MBARI and we adhere to same policy (then add link) so user isn't surprised to leave the site... but this part of the MBARI policy this stuck out to me:
"Our site contains links to other sites. Please remember that our privacy policy does not apply to other sites and that we cannot be responsible for their privacy policies, if any."

So you may just want to tailor it to FathomNet --
We have a google log in, and account information so perhaps something about how we use that.

The first time you connect it says "To continue, Google will share your name, email address, language preference, and profile picture with fathomnet-ff264.firebaseapp.com."

(from MBARI's privacy policy)
"Our policy is that no personal information will be collected about you unless you choose to provide it and that any personal information which you provide us will be safeguarded and not shared with others for any reason."

I don't think we share private info, but if someone submits a collection other users could see their name and organization? So maybe something about that.

-- Again not an expert, these are just the things that stuck out to me.

**Comment by hohonuuli** [comment]
required for Twitter login.

**Comment by kevinsbarnard** [comment]
Not doing third-party auth; won't do this.
