### ISSUE TITLE
Show activity stream for regions/concepts/users that a user follows

### ISSUE THREAD

**Issue by hohonuuli** [fathomnet/community-feedback#111]

**Comment by hohonuuli** [comment]
User selects concept of interest and a date range, and the endpoint would return all the concepts in a date range. 

Another endpoint would return all with paging.

@kevinsbarnard and I discussed that for now we will target individual concepts and not whole branches. Extended trees create a number of problems.

**Comment by hohonuuli** [comment]
For regions, add two endpoints:
- GET with region name, date range
- GET with region name, paged.

**Comment by hohonuuli** [comment]
For people, add the following endpoints:

For bounding box audit table
- GET by verifier, date range
- GET by verfier, paged
- GET by observer, date range
- GET by observer, paged
- GET by contributers_email, date range
- GET by contributers_email, paged

**Comment by hohonuuli** [comment]
Store frequency of notifications in the fathomnet_identity table and then opt-in/opt-out in the `following` table.

**Comment by hohonuuli** [comment]
Tracking feature in <https://github.com/fathomnet/fathomnet-rest-api/tree/feature/111>

**Comment by kevinsbarnard** [comment]
@hohonuuli, I made a separate branch for this before: https://github.com/fathomnet/fathomnet-rest-api/tree/feature/activity

**Comment by hohonuuli** [comment]
@kevinsbarnard Roger. I'll take a look.

**Comment by hohonuuli** [comment]
Backend has been completed in [v1.8.0](https://github.com/fathomnet/fathomnet-rest-api/releases/tag/1.8.0) and published to production.

**Comment by hohonuuli** [comment]
@ermbutler Backend is ready. Handing this task off to you for the UI. Let me know if you need any tweaks or additions to the API. Cheers.
