### ISSUE TITLE
FathomNet Blog link should open in new window

### ISSUE THREAD

**Issue by joostdaniels** [fathomnet/community-feedback#120]
Since it is an external link

**Comment by hohonuuli** [comment]
OMG, I hate links that open new windows.

**Comment by joostdaniels** [comment]
That's fair, but you're taken away from the fathomnet website when you click it, which is unexpected behavior for a menu item like that. Only the logo (or back button) seemingly takes you back.

**Comment by ermbutler** [comment]
This is complete as part of beta 1 launch.
