### ISSUE TITLE
modify FathomNet's about us page terms of use section and FathomNets data use policy page to be in line with official definitions of "terms of use"

### ISSUE THREAD

**Issue by kakanikatija** [fathomnet/community-feedback#124]
Just got off the phone with MBARI's IP lawyer, and he's recommending changes to these two pages. see attached.
<img width="1110" alt="Screen Shot 2023-08-03 at 14 06 15" src="https://github.com/fathomnet/community-feedback/assets/26979643/db2846ec-0ab1-48b3-8dd6-75b7e707c569">
<img width="1138" alt="Screen Shot 2023-08-03 at 14 06 31" src="https://github.com/fathomnet/community-feedback/assets/26979643/9ceeed27-3832-4c56-a309-71a72892372b">

**Comment by kakanikatija** [comment]
@ermbutler this is actually becoming a legal issue now. any chance we can fix this sooner rather than later?

**Comment by ermbutler** [comment]
@hohonuuli  CC: @kevinsbarnard 
I committed a fix for this in the ui codebase on the main branch --- Can you take a look and push this out?

**Comment by hohonuuli** [comment]
@ermbutler Done. Your changes have been tagged in release 1.3.4 and pushed to production.
