### ISSUE TITLE
Scientific Name to Common Name?

### ISSUE THREAD

**Issue by Jordan-Pierce** [fathomnet/community-feedback#125]
Hello, I was looking at the Super Category object detection algorithm in the Model Zoo, and in the `benthic_label_map.json` there's the mapping between species and a common super-class ('fish', 'soft coral', etc.)

I was curious if this mapping was done manually, or if it exists in FathomNet (or the API), or was something else used to do this mapping?

Thanks

Jordan

**Comment by kevinsbarnard** [comment]
Hi Jordan, that mapping was created manually for the model.
