### ISSUE TITLE
CORS missing for /boundingboxes/list/concepts call on homepage

### ISSUE THREAD

**Issue by kevinsbarnard** [fathomnet/community-feedback#133]
CORS header ‘Access-Control-Allow-Origin’ for http://fathomnet.org:8080/boundingboxes/list/concepts missing — error on homepage
![Untitled](https://github.com/fathomnet/community-feedback/assets/40082734/2ca41471-8e54-4ec6-9efd-645c187b81f2)

Not sure where this call is coming from; can't tell if it's actually breaking anything

**Comment by hohonuuli** [comment]
HTTPS endpoint with CORS is <https://fathomnet.org/api/boundingboxes/list/concepts>

**Comment by kevinsbarnard** [comment]
May be fixed, check if this is still the case
