### ISSUE TITLE
Explore filtering - unclear how to get filters to "stick"

### ISSUE THREAD

**Issue by issiecorvi** [fathomnet/community-feedback#147]
After an initial explore search when attempting to further filter data by verified/unverified, etc., it's not clear how to apply the filters and get the results. I was able to get the filter to apply by clicking the search icon button in the main search bar - but it's not intuitive to click that given where the additional filtering interaction occurs. 

<img width="844" alt="Screenshot 2024-02-06 at 10 56 21 AM" src="https://github.com/fathomnet/community-feedback/assets/148128075/61d780ed-7bb1-4200-b530-af05f2f7f068">

**Comment by kakanikatija** [comment]
this is also found in https://github.com/fathomnet/community-feedback/issues/121. i'm closing this issue but leaving the other open.
