### ISSUE TITLE
Fathomnet explorer search not returning all descendants

### ISSUE THREAD

**Issue by Brian-RC-Kennedy** [fathomnet/community-feedback#151]
When I log in and search a high level taxon like Cnidaria I get very few returns in this case, Cnidaria only returns 6 images. I am sure there way more than 6 images that contain Cnidarians and 6 is the largest number I can get. If I narrow to just worms or MBARI for provider I get 0 returns
<img width="1705" alt="Screen Shot 2024-02-15 at 9 45 43 AM" src="https://github.com/fathomnet/community-feedback/assets/114174280/833b4f46-d2eb-45c9-9eac-bcc7bbbbb3bb">

**Comment by hohonuuli** [comment]
@Brian-RC-Kennedy Be default a search does an exact match. So you're only getting things that are explicitly labeled as "Cnidaria". You can extend the search to descendants by selecting a Taxaonomy provider (e.g. mbari). 

![Screenshot 2024-02-15 at 8 54 50 AM](https://github.com/fathomnet/community-feedback/assets/282941/812a877f-e273-4768-b262-53ce9a04daa2)

**Comment by hohonuuli** [comment]
Side note for myself. Selecting "Cnidaria" with the "fathomnet" taxa provider hits this bug: fathomnet/fathomnet-rest-api#24. 

Sanity check at <https://fathomnet.org/worms/taxa/descendants/Cnidaria>, which is where the data originates, works fine. When it gets munged through <https://fathomnet.org/api/taxa/query/fathomnet/Cnidaria> It returns:

```json
{
    "_links": {
        "self": [
            {
                "href": "[/taxa/query/fathomnet/Cnidaria](https://fathomnet.org/taxa/query/fathomnet/Cnidaria)",
                "templated": false
            }
        ]
    },
    "_embedded": {
        "errors": [
            {
                "message": "Internal Server Error: Client 'fastworms': Error decoding HTTP response body: Error decoding JSON stream for type [FWTaxa]: Error decoding property [List children] of type [class org.fathomnet.services.taxa.FastWormsTaxaProvider$FWTaxa]: Error decoding property [List children] of type [class org.fathomnet.services.taxa.FastWormsTaxaProvider$FWTaxa]: Error decoding property [List children] of type [class org.fathomnet.services.taxa.FastWormsTaxaProvider$FWTaxa]: Error decoding property [List children] of type [class org.fathomnet.services.taxa.FastWormsTaxaProvider$FWTaxa]: Error decoding property [List children] of type [class org.fathomnet.services.taxa.FastWormsTaxaProvider$FWTaxa]: Error decoding property [List children] of type [class org.fathomnet.services.taxa.FastWormsTaxaProvider$FWTaxa]: Error decoding property [List children] of type [class org.fathomnet.services.taxa.FastWormsTaxaProvider$FWTaxa]: Error decoding property [List children] of type [class org.fathomnet.services.taxa.FastWormsTaxaProvider$FWTaxa]: Error decoding property [List children] of type [class org.fathomnet.services.taxa.FastWormsTaxaProvider$FWTaxa]: Maximum depth exceeded while deserializing. The maximum nesting depth can be increased, if necessary, using the micronaut.serde.maximum-nesting-depth config property."
            }
        ]
    },
    "message": "Internal Server Error"
}
```

Note that the max depth isn't actually being exceed while deserializing, as mentioned in the error. It looks like I'm hitting a bug between micronaut and the underlying netty server.

**Comment by hohonuuli** [comment]
More notes on the different taxa providers:
-  `mbari` - MBARI's KB works fine. <https://fathomnet.org/api/taxa/query/mbari/Cnidaria> 
- `worms` - The WoRMS API is way too slow to use for high level taxa (See https://fathomnet.org/api/taxa/query/worms/Cnidaria, it will timeout). That's out of our control. 
- `fathomnet` - It processes a fairly large tree for Cnidraria (40834 names) and that's tanking when fathomnet deserializes it and tries to normalize the tree to fathom net's taxa structure. The call to <https://fathomnet.org/worms/taxa/descendants/Cnidaria> returns about 4.2MB of structured json data. Formatted it's about 300k lines

**Comment by Brian-RC-Kennedy** [comment]
@hohonuuli Thanks for the quick response. I can't get anything to show up even using MBARI as the provider and selecting all descendants. I am sorry if I am being dense and just missed something. I am using Chrome version 121.0.6167.160 on a Mac running 12.2.1 (21D62) in case there is a problem beyond me not understanding. This video is what I see when I try get all the descendants. Thanks

https://github.com/fathomnet/community-feedback/assets/114174280/86bc600d-2e96-4303-96a1-04ad9ca32f1e

**Comment by hohonuuli** [comment]
@Brian-RC-Kennedy In your video, it looks like you're not giving the initial query (Cnidaria + mbari taxa provider) enough time to complete the request. On my very fast network, it takes almost 6 seconds to complete the Cnidaria request; you're requesting a very large chunk of information so be patient. 

![Screenshot 2024-02-15 at 10 28 33 AM](https://github.com/fathomnet/community-feedback/assets/282941/4ed1e010-434c-4a3b-8629-b3772d2608b5)

**Comment by Brian-RC-Kennedy** [comment]
@hohonuuli thank you I understand now. May I suggest a spinning wheel or something for the user to know when it is processing vs no results.

**Comment by hohonuuli** [comment]
>  May I suggest a spinning wheel or something for the user to know when it is processing vs no results.

You may. That's a great suggestion.

**Comment by hohonuuli** [comment]
@Brian-RC-Kennedy I've added your suggestion in issue #152
