### ISSUE TITLE
add privacy policy to fathomnet website

### ISSUE THREAD

**Issue by kakanikatija** [fathomnet/community-feedback#156]
Need to create a page at HTTPS://WWW.FATHOMNET.ORG/PRIVACY; I will have text ready for us to include shortly. Currently we link to MBARI's privacy policy, which no longer applies.

**Comment by ermbutler** [comment]
Policy is live https://fathomnet.org/fathomnet/#/privacy

Closing as complete, but please let me know if there is more to be done here! cc: @kevinsbarnard @hohonuuli
