### ISSUE TITLE
Update legal docs on FathomNet website

### ISSUE THREAD

**Issue by kakanikatija** [fathomnet/community-feedback#158]
FathomNet Terms of Use: https://docs.google.com/document/d/1wf2SPJFCfizsk4vk5mwd-dm02kilNY9aHOWNi_nEHdg/edit?usp=sharing
FathomNet Privacy Policy: https://docs.google.com/document/d/1DjYdI8OBnkNWUYxR1bWvxtq5v1ki07iti6etHhlpHzA/edit?usp=sharing
FathomNet Data Use Policy: https://docs.google.com/document/d/1KoLOATrNPV7jGWAmYYH0aNY4zV_N1x4vcGpXEJAAPwE/edit?usp=sharing

**Comment by ermbutler** [comment]
Terms of Use https://fathomnet.org/fathomnet/#/license
Privacy Policy https://fathomnet.org/fathomnet/#/privacy
Data Use Policy https://fathomnet.org/fathomnet/#/about#datause

I see a link in terms of use that is not properly linking - written like "HTTPS://WWW.FATHOMNET.ORG/PRIVACY" so I am going to create a bug issue to fix that. I will poke around again to see if anything else, but I will close this task as complete, 

Please let me know if there is more to be done here! cc: @kevinsbarnard @hohonuuli
