### ISSUE TITLE
Add links to Huggingface from FathomNet webpage

### ISSUE THREAD

**Issue by eor314** [fathomnet/community-feedback#16]
Since we'll be recommending that users post their models via Zenodo, we should add a link to the Zenodo community on the webapage. Specifically in **Join the FathomNet Community** item 5 and the **Quick External Links** list on the about page. 

This one will do the trick: https://zenodo.org/communities/fathomnot/?page=1&size=20

**Comment by kevinsbarnard** [comment]
Let's do this -- add link to Model Zoo directly

https://hf.co/fathomnet

**Comment by hohonuuli** [comment]
Duplicated by #123

**Comment by kevinsbarnard** [comment]
@ermbutler Will add "Model Zoo" link
