### ISSUE TITLE
Broken link on terms of use

### ISSUE THREAD

**Issue by ermbutler** [fathomnet/community-feedback#161]
Link in terms of use https://fathomnet.org/fathomnet/#/license that is not properly linking - 

Link is written and linking to all uppercase fathomnet.org/privacy "https://www.fathomnet.org/PRIVACY" but need to be updated to https://fathomnet.org/fathomnet/#/privacy

**Comment by kevinsbarnard** [comment]
Related to #158 

Thanks for adding this @ermbutler!
