### ISSUE TITLE
Missing Images

### ISSUE THREAD

**Issue by lauravchrobak** [fathomnet/community-feedback#162]
In processing the FN data I found that a few images (the 8 listed below) have a missing width and height fields. I intended to grab the width and height from the actual image in their associated url and found that the urls themselves do not link to an image (they show a blank page). For example, 
`https://fathomnet.org/static/m3/framegrabs/Doc%20Ricketts/images/1024/20180506T143452Z-0daf6504-a381-40c8-ab7b-cf6e20cc121a.png `.

`
28dd37f3-4439-4062-b3c9-f19ac86bee62,
50199917-2d68-4df7-8410-bdd52797d34a,
5ecc9b39-18f1-4c26-b7de-81517356745e,
831dc6c9-8278-402d-ba06-e12c831e8d96,
f7e85856-ab2b-44f4-8a59-7fccd471f925,
e183ff9c-60e8-441e-b219-9a2fc79d3021,
5c32e916-3240-4a06-a3f0-42c4c6909d9f,
 99580059-1224-45f4-bf83-0a9cf8c49a1a
`
These could be manually fixed but also perhaps a test could be added wherein to submit data a test runs to check that the image exists.

**Comment by hohonuuli** [comment]
@lauravchrobak Just a note that all images are checked for presence/absence every month. If an image isn't found it's `valid` field is set to `false`, and the image owner is notified. (`true` means the image can be fetched). You can use the `valid` field to filter out missing images. 


Here's an example: <http://fathomnet.org:8080/images/query/url/https%3A%2F%2Ffathomnet.org%2Fstatic%2Fm3%2Fframegrabs%2FDoc%2520Ricketts%2Fimages%2F1024%2F20180506T143452Z-0daf6504-a381-40c8-ab7b-cf6e20cc121a.png> returns:

```json
{
  "uuid": "50199917-2d68-4df7-8410-bdd52797d34a",
  "url": "https://fathomnet.org/static/m3/framegrabs/Doc%20Ricketts/images/1024/20180506T143452Z-0daf6504-a381-40c8-ab7b-cf6e20cc121a.png",
  "contributorsEmail": "brian@mbari.org",
  "imagingType": "ROV",
  "salinity": 34.44499969482422,
  "temperatureCelsius": 4.053999900817871,
  "oxygenMlL": 0.3659999966621399,
  "pressureDbar": 977.7000122070312,
  "depthMeters": 971.5,
  "latitude": 36.216119,
  "longitude": -122.53199,
  "timestamp": "2018-05-06T14:34:52.052Z",
  "createdTimestamp": "2022-05-24T23:31:50.292Z",
  "lastValidation": "2024-07-25T07:02:46.990704Z",
  "valid": false,
  "lastUpdatedTimestamp": "2024-07-25T07:02:46.999Z",
  "tags": [
    {
      "uuid": "94f89aa8-636b-46a0-a948-b34d8e5abb73",
      "key": "source",
      "value": "MBARI/VARS",
      "mediaType": "text/plain"
    }
  ],
  "boundingBoxes": [
    {
      "uuid": "c3b7debd-b3fa-4cd9-9ba5-9fffb2562200",
      "userDefinedKey": "b5ce98c3-b248-4d4f-996f-4441722fc21e",
      "concept": "Planctoteuthis oligobessa",
      "height": 739,
      "observer": "schlin",
      "width": 1169,
      "x": 502,
      "y": 333,
      "rejected": false,
      "verified": false,
      "lastUpdatedTimestamp": "2022-05-24T23:31:51.295Z"
    }
  ]
```

The fathomnet API docs are at <http://fathomnet.org:8080/swagger-ui#/>

**Comment by lauravchrobak** [comment]
Great thanks, I will check for this flag in my code!
