### ISSUE TITLE
Add sentence to explicitly indicate FathomNet is not to be used as an occurrence dataset

### ISSUE THREAD

**Issue by kevinsbarnard** [fathomnet/community-feedback#164]
Add a sentence to the about us section or somewhere more visible to indicate that FathomNet is not to be used as an occurrence dataset

from @kakanikatija

**Comment by ermbutler** [comment]
@kakanikatija would here work? Language TBD see third bullet in screenshot "Researchers utilizing FathomNet, please note that FathomNet is not to be used as an occurrence dataset"

![image](https://github.com/user-attachments/assets/f9ecca7e-4b65-4454-8f96-95d7ba592db5)

**Comment by kakanikatija** [comment]
i'm a little wary of adding that to the bullet points. perhaps we add a sentence after "Contributors can visit this user guide..." that includes "Please note that FathomNet is not intended to be used as an occurrence dataset."

**Comment by ermbutler** [comment]
Ok! Here is what that would look like:
![image](https://github.com/user-attachments/assets/1dbd6503-a47b-48aa-8991-8ae6b39429e0)

**Comment by kakanikatija** [comment]
Great!
