### ISSUE TITLE
Show contribution stats on a users about page

### ISSUE THREAD

**Issue by hohonuuli** [fathomnet/community-feedback#27]

**Comment by hohonuuli** [comment]
![Screenshot 2023-02-08 at 10 48 53 AM](https://user-images.githubusercontent.com/282941/217624191-d9364279-3a1d-4f90-9367-968580479492.png)

Requires search/count by observer to be added to geoimage search

**Comment by hohonuuli** [comment]
@ermbutler 

- Query uploads and annotations by user
- Query by organization and job title.
- How to query by institution? Add field to users profile.
- How to store social media links? Or should they just be in the bio and the bio will convert them to hyperlinks

Katie has mockup for users profile editing page

**Comment by hohonuuli** [comment]
What social media platforms do we want to link in?

**Comment by hohonuuli** [comment]
Do we want to add additional workplace or affiliated institution? How to link it to the added institutions list.

Adding multiple institutions would be a 2nd phase.

**Comment by hohonuuli** [comment]
Adding multiple social logins in phase 2

**Comment by hohonuuli** [comment]
How to implement badges ... stage these sooner rather than later.

What are all the badges? Early adopter - 1 week after next workshop, code contributor

**Comment by hohonuuli** [comment]
Related #39 and #40

**Comment by hohonuuli** [comment]
@kakanikatija says "Follow" is important feature. That's back end too.

**Comment by hohonuuli** [comment]
What's the definition of activity? made an id, commented on, verified, upload. 

Search by observer will be added as another issue which will address part of this. I think upload is covered already.  Search by comment, verified will require API additions.

**Comment by hohonuuli** [comment]
The "sort" under activity is by date. Filters are by concept, upload, identification, verification, localizations

**Comment by hohonuuli** [comment]
Posted on FathomNet's slack:

FathomNet API 1.4.1 has been released. Changes in this release are to support showing a users activity.

1. [Find bounding boxes by observer](http://fathomnet.org:8080/swagger-ui#/default/findByObserver)’s UUID. The results can be paged using size and page query params. They can also be sorted by any field using a sort param. A full example is: http://fathomnet.org:8080/boundingboxes/query/observer/E5F6C1AA-97B2-46FC-8316-503B0C3E1FF7?sort=lastUpdatedTimestamp,DESC&size=10&page=0
2. [Find bounding boxes by verifier’s UUID](http://fathomnet.org:8080/swagger-ui#/default/findByVerifier).  This also accepts size, page and sort query params. Full example: http://fathomnet.org:8080/boundingboxes/query/verifier/E5F6C1AA-97B2-46FC-8316-503B0C3E1FF7?sort=lastUpdatedTimestamp,DESC&size=10&page=10

Erin, This should help with your activities page. Note the sort param in the query examples. That will give the most recent changes first. The paged result contains a totalSize field for the number of boxes in the query that’s useful for a summary stat.

**Comment by ermbutler** [comment]
Erin in progress
