### ISSUE TITLE
[Error] Unexpected end of JSON input / Failed to fetch

### ISSUE THREAD

**Issue by ghost** [fathomnet/community-feedback#3]
When attempting to submit my first .csv, I received a couple of errors (see below)

Is this an issue with my .csv or write access related?

**chirotest.csv**:

```
concept,image,x,y,width,height,depth,timestamp
Chiroteuthis calyx,https://fathomnet.livestreamoceanographic.org/staging-ground/tropicofdan/concept/chiroteuthiscalyx/chirotest.png,891,48,302,1013,136,2021-08-14T04:30:56Z
```

![Screen Shot 2021-09-30 at 10 27 43 PM](https://user-images.githubusercontent.com/91396350/135570532-611a9f96-bde1-4f40-8f85-e63d93ed32f0.png)
![Screen Shot 2021-09-30 at 10 28 21 PM](https://user-images.githubusercontent.com/91396350/135570531-2be3b8dd-47c7-4219-96a2-a1e869fe4aaa.png)

**Comment by kakanikatija** [comment]
Hi Dan! I think this is linked to write access. I sent you an email about that earlier today. Will gladly go over all this with you when we meet to discuss in a few weeks. Keep the feedback coming!

**Comment by hohonuuli** [comment]
@tropicofdan Thanks for letting us know about that. We're still working out how to grant elevated permissions to user accounts. But new accounts really shouldn't be seeing that button. As @kakanikatija mentioned, the server will reject upload attempts for users without the correct access permissions.

**Comment by ghost** [comment]
@hohonuuli Roger, thanks for the heads up. As for write access, it was discussed with @kakanikatija earlier in the day and we're good to go on that for now.
