### ISSUE TITLE
enable search on the people page

### ISSUE THREAD

**Issue by kakanikatija** [fathomnet/community-feedback#32]
it is so hard to find people with the existing UI

**Comment by hohonuuli** [comment]
<http://fathomnet.org/fathomnet/#/account/people>

**Comment by hohonuuli** [comment]
GanttStart: 2022-09-15
GanttDue:  2022-09-15

**Comment by hohonuuli** [comment]
@ermbutler Initially, Add API endpoint.

**Comment by hohonuuli** [comment]
Katie's mockup allows search by people or institutions. 
![Screenshot 2023-02-08 at 10 31 02 AM](https://user-images.githubusercontent.com/282941/217620340-5b49cfb0-99e8-4b89-b672-4e3f0ea132b6.png)

Sorts by top contributors, A-Z, Z-A. What's the default ... alphabetical

**Comment by hohonuuli** [comment]
Filter has lots of power and would require changes on front and back end. That would be the 2nd phase of search. 1st phase would be just the basic search

**Comment by hohonuuli** [comment]
Add leader boards in phase 2

**Comment by hohonuuli** [comment]
The people page will be replaced by the community page. This will change navigation a bit.

**Comment by hohonuuli** [comment]
Current admin function for people will still be there but only used by admin.

**Comment by hohonuuli** [comment]
for @hohonuuli : Add an endpoint to query for users/institutions matching a substring. The results need to be paginated and sorted via the endpoint.

**Comment by hohonuuli** [comment]
See:

- <http://fathomnet.org:8080/swagger-ui#/default/findByDisplayName>
- <http://fathomnet.org:8080/swagger-ui#/default/findByOrganization>
