### ISSUE TITLE
How to track image preprocessing?

### ISSUE THREAD

**Issue by hohonuuli** [fathomnet/community-feedback#46]
In general, we discourage image preprocessing. If image is preprocessed perhaps to capture a human readable description of the pre-processing (color-corrected, particles removed, etc.). This is mostly documentation. Add to the medium article on submitting  data.

**Comment by hohonuuli** [comment]
Option to embed as EXIF already exists.

**Comment by kevinsbarnard** [comment]
Other options for metadata that describe preprocessing, closing as not planned
