### ISSUE TITLE
Allow users to select concepts of interest

### ISSUE THREAD

**Issue by hohonuuli** [fathomnet/community-feedback#65]
Create separate user area that allows them to select concepts of interest and review problems in taxonomy, get a message/prompt when something is added to FathomNet that matches their search terms

**Comment by hohonuuli** [comment]
![Image](https://user-images.githubusercontent.com/282941/217634062-3bfafde2-72cf-4bc5-a1c9-d647fcf19e0d.png)



![Image](https://user-images.githubusercontent.com/282941/217634075-86e39e6c-8dd0-45d8-931d-5cc78676f8d9.png)



![Image](https://user-images.githubusercontent.com/282941/217634095-b53c12eb-3be1-47f1-bae2-61278b847975.png)

**Comment by hohonuuli** [comment]
Following a species shows the number of IDs per species you follow.

Following a location shows the number of IDs in the region you follow.

Following a user shows their comments, also same activities of they upload, id, verify or suggest an alternate id

**Comment by hohonuuli** [comment]
Search by regions would require some thinking about best implementation. We would need to do some state tracking for this to work.

**Comment by hohonuuli** [comment]
This is three separate tasks:

- follow concepts
- follow regions
- follow people

**Comment by ermbutler** [comment]
Still to do -- this is the backend task for #97

**Comment by hohonuuli** [comment]
Table. 6 columns: id, uuid, user id, follow key (concept, region, people), target, and opt-in for notifications.

Notification frequency is in fathomnet_idenitity table

**Comment by hohonuuli** [comment]
As concepts get changed we would need to update the followed concept?

**Comment by hohonuuli** [comment]
API endpoints: - takes user authentication as arg and key + value (POST, PUT, DELETE, GET) Get for both all by user and one by UUID

**Comment by hohonuuli** [comment]
I've added endpoints for CRUD operations to allow users to register with topics of interest. (e.g. concept, region, person). This should meet this request. Note that what isn't discussed in this issue is what to do with that info. I think the idea is to generate a feed of activity. I'll post a release of this tomorrow and close this issue. The UI followup for selecting a concept of interest is in #97. This is also related to #54 ... but where's the issue for allowing users to specify the frequency of notifications?

**Comment by hohonuuli** [comment]
Ahh. The Activity stream task is in #111
