### ISSUE TITLE
Track contributor names at all stages: submitter, annotator, localizer, verifier, etc.; display those names on the website

### ISSUE THREAD

**Issue by hohonuuli** [fathomnet/community-feedback#67]
Tracking is done. Need to display on web site.

**Comment by hohonuuli** [comment]
Need a UI to display history. See #45

**Comment by hohonuuli** [comment]
Maybe show history under image of last annotation that was hovered over. This history would show who verified it

**Comment by hohonuuli** [comment]
Current behavior for showing verified and changing verification status in FathomNet is pretty smooth though. Maybe keep that as is and still display it in the history?

**Comment by ermbutler** [comment]
Backend ready but not exposing some dates. Front end will compare to make the "what changed" part of it.

Todo: confirm which design is final

**Comment by hohonuuli** [comment]
Backend now exposes dates.

**Comment by ermbutler** [comment]
Erin in progress using this for activity list
