### ISSUE TITLE
Incorporate ORCID numbers into user biographies/registration so that contributions can be tracked and added to FathomNet version DOI

### ISSUE THREAD

**Issue by hohonuuli** [fathomnet/community-feedback#68]

**Comment by hohonuuli** [comment]
<https://orcid.org>

Details for Authenticating an ORCID ID is [here](https://info.orcid.org/documentation/api-tutorials/api-tutorial-get-and-authenticated-orcid-id/)

**Comment by hohonuuli** [comment]
How do we express this in the UI?

**Comment by hohonuuli** [comment]
Should we wire it in via Firebase (if we have paid firebase and they support OAuth connect)

**Comment by hohonuuli** [comment]
ORCID supports open API connect. We have the option of wiring that into firebase. <https://info.orcid.org/orcid-openid-connect-and-implicit-authentication/>

**Comment by kevinsbarnard** [comment]
Get charge number for OpenID Connect

**Comment by hohonuuli** [comment]
I've upgraded firebase to a paid tier. We can now add OpenID Connect providers. @kevinsbarnard has permissions to to that.

**Comment by hohonuuli** [comment]
<https://github.com/ORCID/orcid-auth-widget>

**Comment by ermbutler** [comment]
@ermbutler to pick up adding input box to profile and showing on user profile

```
{
  "jobTitle": "string",
  "organization": "string",
  "profile": "string",
  "displayName": "string",
  "orcid": "string"
}
```

**Comment by hohonuuli** [comment]
http://fathomnet.org:8080/swagger-ui#/default/updateUserData

**Comment by ermbutler** [comment]
Note consulting this for presentation: https://info.orcid.org/brand-guidelines/#h-the-orcid-name

> When talking or writing about ORCID:
> DO
> Use “ORCID” as a noun to refer only to the organization and the noun phrase “ORCID identifier” or “ORCID iD” (lower case i, upper case D) to refer to the identifier itself (e.g., “ORCID offers unique identifiers, known as ORCID iDs”).
> Use the phrase “ORCID record” to refer to an ORCID account in the ORCID Registry containing information about the ORCID iD holder.
> Ensure the title of your publication makes clear that it’s about ORCID and not by ORCID:
> Yes: “Sharing your ORCID record”
> No: “The ORCID guide to sharing your record”
> DON’T
> Use “Open Researcher and Contributor Identifier” to represent the name of ORCID or the identifier; instead simply use “ORCID”.
> Use the word “ORCIDs” to refer to ORCID iDs.
> Use the word “ORCID” to refer to services other than ORCID.

**Comment by ermbutler** [comment]
Additionally

> We do not currently allow references to authorized ORCID iDs without using the iD icon.
> 
> The ORCID iD icon and associated text should link to an ORCID record URL. 
> 
> Icons should only be used for authenticated ORCID iDs.
