### ISSUE TITLE
FathomNet favicon

### ISSUE THREAD

**Issue by kakanikatija** [fathomnet/community-feedback#7]
We should replace the favicon (or whatever it's called) on fathomnet.org. Currently it's MBARI's. I have the file when you need it @hohonuuli.

**Comment by ermbutler** [comment]
Can you send the file to me when you get a chance? I can pick this up.

**Comment by ermbutler** [comment]
Pushed icon to develop branch -- chose the white over dark logo, easier to see.
![image](https://user-images.githubusercontent.com/17165227/151623993-6c435476-7c2d-4a0d-9c5b-82f8bfcf2844.png)

**Comment by hohonuuli** [comment]
Deployed in [this release](https://github.com/fathomnet/fathomnet-web-ui/releases/tag/1.0.1)
