### ISSUE TITLE
How to track annotation confidence?

### ISSUE THREAD

**Issue by hohonuuli** [fathomnet/community-feedback#71]
Provide confidence levels for annotations before and after data are uploaded to FathomNet
Taxonomist should be able to assign a confidence level
Person requesting change should provide explanation for suggestion
Comment stream for each annotation

track confidence if user has an actual sample of the animal in the photograph.

**Comment by claudenozeres** [comment]
@hohonuuli, are you looking for examples of how this is done (e.g., on projects in BIIGLE), proposing best practices, or noting is an issue in FathomNet to resolve? Thanks! Claude

**Comment by hohonuuli** [comment]
@claudenozeres We're open to guidance on this one. This issue was created from notes from user feedback surveys.

**Comment by claudenozeres** [comment]
Thanks @hohonuuli . I mentioned that because a colleague (Barbara Neves) working with underwater video imagery did a recent ICES presentation on that topic. Will ask to share. Quality control is something we wonder about--going beyond annotations with names.

**Comment by hohonuuli** [comment]
@claudenozeres Yes, please share the presentation!

**Comment by hohonuuli** [comment]
We track changes and allow comments now. Is this sufficient?

![Screenshot 2024-02-27 at 2 41 45 PM](https://github.com/fathomnet/community-feedback/assets/282941/7ffcb24f-0cc3-4535-9fa5-f84a178dddc0)

**Comment by hohonuuli** [comment]
Do we want to capture the "confidence" from ML models?

**Comment by claudenozeres** [comment]
Is a step, but I would not say it is adequate. If not clear/obvious, I could expound on this.

**Comment by hohonuuli** [comment]
@claudenozeres Just a note that we're currently prioritizing based on the amount of engineering resources we have.
