### ISSUE TITLE
page load time feature request

### ISSUE THREAD

**Issue by jeffday** [fathomnet/community-feedback#9]
howdy y'all

apologies if this is already on your radar/roadmap. given that the majority of images being served from fathomnet are quite large, and that thumbnails are dynamically resized versions of the full-res image, loading a page of thumbnails can be slow. the network tab from pulling a page of thumbnails for 'atolla' shows i'm downloading about 12MB of images:

![Screen Shot 2021-10-06 at 5 03 51 PM](https://user-images.githubusercontent.com/2001310/136290133-e59a16cd-47f4-4008-b28a-e00717d0ad4c.png)

transcoding from PNG to JPG could net you an easy file size win. there's also always adding a CDN in front of things, although that can be expensive depending on volume.

**Comment by hohonuuli** [comment]
Yes. Thanks for pointing out we're lazy programmers. ;-) 

Just some notes. Thumbnails will likely come later (maybe). Also, because the focus of FathomNet is machine learning rather than content delivery, we (MBARI) are avoiding the use of jpg to minimize compression artifacts. (PNGs are lossless, JPGs are lossy)

**Comment by hohonuuli** [comment]
Note that in MBARIs internal annotation systems, we do maintain both a JPG and PNG to use for different applications (e.g. content delivery vs ML). For simplicity we decided not to do that in the first iteration of FathomNet.

**Comment by jeffday** [comment]
Yeah, the prioritization and design process make total sense, just wanted to put something down in words in the off-chance it hadn't been considered. Thanks for the quick reply, Brian!
