### ISSUE TITLE
Add UI for annotation history to image detail page

### ISSUE THREAD

**Issue by kevinsbarnard** [fathomnet/community-feedback#96]
Blocked by #45

**Comment by ermbutler** [comment]
Note (from slack) Adding lastUpdatedTimestamp to bounding boxes. This will allow better history displays of changes. Examples:
 http://fathomnet.org:8080/boundingboxes/audit/userdefinedkey/c9ff671c-e435-4228-6066-4551671cbb1e
http://fathomnet.org:8080/boundingboxes/audit/uuid/ca75f248-20e3-46e6-955f-78ed196c7902

**Comment by ermbutler** [comment]
Design:



![Image](https://user-images.githubusercontent.com/17165227/224426018-10b286dc-227b-42ac-940e-1ca48c6a0ef7.png)



![Image](https://user-images.githubusercontent.com/17165227/224425979-7de67dd1-930a-44c5-b711-60cadf9d32d5.png)



![Image](https://user-images.githubusercontent.com/17165227/224426056-9735b758-53ee-4c2f-bc70-0ad43076892b.png)

**Comment by ermbutler** [comment]
This is what I wrote down from last meeting re: comments--
- Can multiple people verify?
    - Not for now?
- Suggest after it is verified?
    - No
- Comment after it is verified
    - Yes
